- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/wordpress.conf
  notify: Reload Nginx

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/wordpress.conf
    dest: /etc/nginx/sites-enabled/wordpress.conf
    state: link
  notify: Reload Nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx
