- name: Install MariaDB server
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
      - ufw
    state: present
    update_cache: yes

- name: Enable and start MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Configure MariaDB to listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    state: present
  notify: Restart MariaDB

- name: Create MySQL database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user with remote access
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_pass }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

