- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes



- name: Remove default Nginx config
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default.conf
  ignore_errors: yes
  notify: Reload nginx


- name: Deploy Nginx reverse proxy config
  ansible.builtin.template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/{{ server_name }}.conf
    mode: 0644
  notify: Reload nginx

- name: Ensure Nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
