---
- name: Download and unpack WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html
    remote_src: yes
    extra_opts:
      - --strip-components=1
  become: yes

- name: Correct permissions on WordPress directory
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
  become: yes

- name: Configure wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
  become: yes
